# -*- coding: utf-8 -*-
"""ECLAT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nn86A5604XPzxcYgvwmBPiwNcnpkcdmw
"""

import pandas as pd
import numpy as np
!pip install pyECLAT

df=pd.read_csv(r"/content/Market_Basket_Optimisation.csv",header=None)

df.info()

for col in df.columns:
  print(df[col].name,df[col].value_counts().unique())

df.describe()

df.isnull().sum()

from pyECLAT import ECLAT
import matplotlib.pyplot as plt
model=ECLAT(data=df,verbose=True)

model.uniq_

get_ECLAT_indexes,get_ECLAT_supports=model.fit(min_support=0.02,min_combination=1,max_combination=3,separator='&',verbose=True)

print(get_ECLAT_indexes)
print(get_ECLAT_supports)

